################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1


###################
### MY PROGRAMS ###
###################

$terminal    = kitty
$fileManager = kitty -e yazi
$browser     = firefox
$menu        = rofi -show drun -show-icons -theme ~/.config/rofi/theme.rasi
$clipboard   = cliphist list | rofi -dmenu -theme ~/.config/rofi/theme.rasi | cliphist decode | wl-copy
$logout      = wlogout
$lock        = hyprlock


####################
### SOURCE FILES ###
####################

source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/look.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/binds.conf
